# Generated by Django 4.2.3 on 2023-07-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('brand', models.CharField(max_length=11)),
                ('model', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('bodywork', models.CharField(max_length=16)),
                ('plate', models.CharField(max_length=7)),
                ('fuel', models.CharField(max_length=18)),
                ('displacement', models.CharField(max_length=5)),
                ('wheel_drive', models.CharField(max_length=9)),
                ('gas_tank', models.CharField(max_length=14)),
                ('net_weight', models.IntegerField()),
                ('goss_weight', models.IntegerField()),
                ('rows_seats', models.IntegerField()),
                ('mileage_km', models.IntegerField()),
                ('original_tire_code', models.CharField(max_length=9)),
                ('installed_tire_code', models.CharField(max_length=9)),
                ('car_use', models.CharField(max_length=18)),
                ('extra_charge', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('dni_ruc', models.CharField(max_length=11)),
                ('phone_number', models.CharField(max_length=9)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DesignedSpring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osis_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Spring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wire', models.DecimalField(decimal_places=2, max_digits=4)),
                ('diam_ext1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diam_ext2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diam_int1', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('diam_int2', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('coils', models.DecimalField(decimal_places=3, max_digits=6)),
                ('coil_direction', models.CharField(max_length=20)),
                ('end1', models.CharField(default='-', max_length=50)),
                ('luz1', models.IntegerField()),
                ('detail1_end1', models.CharField(default='-', max_length=15)),
                ('detail2_end1', models.CharField(default='-', max_length=15)),
                ('detail3_end1', models.CharField(default='-', max_length=15)),
                ('eccentricity1', models.DecimalField(decimal_places=3, max_digits=6)),
                ('end2', models.CharField(default='-', max_length=50)),
                ('luz2', models.IntegerField()),
                ('detail1_end2', models.CharField(default='-', max_length=15)),
                ('detail2_end2', models.CharField(default='-', max_length=15)),
                ('detail3_end2', models.CharField(default='-', max_length=15)),
                ('eccentricity2', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='SampleSpring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spring_type', models.CharField(max_length=10)),
                ('spring_position', models.CharField(max_length=9)),
                ('suspension_type', models.CharField(max_length=16)),
                ('source', models.CharField(max_length=15)),
                ('coil_spacer', models.CharField(max_length=20)),
                ('spacer_height', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryapp.car')),
                ('spring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryapp.spring')),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlative', models.IntegerField()),
                ('status', models.CharField(max_length=11)),
                ('registration_date', models.DateField()),
                ('development', models.CharField(max_length=12)),
                ('request_reason', models.CharField(max_length=100)),
                ('aplication', models.CharField(max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryapp.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryapp.client')),
                ('sample_spring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryapp.samplespring')),
            ],
        ),
    ]
