# Generated by Django 4.2.3 on 2023-07-20 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('f2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('f3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('f4', models.DecimalField(decimal_places=2, max_digits=6)),
                ('f5', models.DecimalField(decimal_places=2, max_digits=6)),
                ('f6', models.DecimalField(decimal_places=2, max_digits=6)),
                ('f7', models.DecimalField(decimal_places=2, max_digits=6)),
                ('f8', models.DecimalField(decimal_places=2, max_digits=6)),
                ('f9', models.DecimalField(decimal_places=2, max_digits=6)),
                ('f10', models.DecimalField(decimal_places=2, max_digits=6)),
                ('l1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('l2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('l3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('l4', models.DecimalField(decimal_places=2, max_digits=6)),
                ('l5', models.DecimalField(decimal_places=2, max_digits=6)),
                ('l6', models.DecimalField(decimal_places=2, max_digits=6)),
                ('l7', models.DecimalField(decimal_places=2, max_digits=6)),
                ('l8', models.DecimalField(decimal_places=2, max_digits=6)),
                ('l9', models.DecimalField(decimal_places=2, max_digits=6)),
                ('l10', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ProducedSpring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osis_code', models.IntegerField()),
                ('date', models.DateField()),
                ('spring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryapp.spring')),
            ],
        ),
        migrations.CreateModel(
            name='SpringPointsDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('coils', models.DecimalField(decimal_places=3, max_digits=6)),
                ('include_point', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='designedspring',
            name='l_4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='designedspring',
            name='l_charg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='designedspring',
            name='l_inst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='designedspring',
            name='l_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='designedspring',
            name='lda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='designedspring',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='designedspring',
            name='raw_material',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='designedspring',
            name='selected',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='designedspring',
            name='spring',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='queryapp.spring'),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='designedspring',
            name='transition_point',
            field=models.IntegerField(null=1),
            preserve_default=1,
        ),
        migrations.AddField(
            model_name='designedspring',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.CreateModel(
            name='QualityControlReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=15)),
                ('production_requirement', models.CharField(max_length=15)),
                ('work_order', models.CharField(max_length=15)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryapp.design')),
                ('designed_spring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryapp.designedspring')),
                ('produced_spring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='queryapp.producedspring')),
            ],
        ),
        migrations.AddField(
            model_name='spring',
            name='cargo_control',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.CASCADE, to='queryapp.cargocontrol'),
            preserve_default=1,
        ),
    ]
