# Generated by Django 4.2.3 on 2023-07-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpringTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alambre', models.DecimalField(decimal_places=2, max_digits=4)),
                ('diam', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vueltas', models.DecimalField(decimal_places=3, max_digits=6)),
                ('longitud', models.DecimalField(decimal_places=2, max_digits=6)),
                ('luz1', models.IntegerField()),
                ('luz2', models.IntegerField()),
                ('diam_int1', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('extremo1', models.CharField(default='-', max_length=50)),
                ('vuelta_red1', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('diam_int2', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('extremo2', models.CharField(default='-', max_length=50)),
                ('vuelta_red2', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('grado', models.IntegerField(default=2)),
            ],
        ),
    ]
