# Generated by Django 4.2.3 on 2023-09-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dbauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, null=1)),
                ('password', models.CharField(max_length=30, null=1)),
                ('token', models.CharField(max_length=30, null=1)),
                ('user_type', models.IntegerField(null=1)),
            ],
        ),
    ]
