# Generated by Django 4.2.3 on 2023-07-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0002_cargocontrol_producedspring_springpointsdesign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='bodywork',
            field=models.CharField(max_length=16, null=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_use',
            field=models.CharField(max_length=18, null=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='displacement',
            field=models.CharField(max_length=5, null=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='extra_charge',
            field=models.CharField(max_length=25, null=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(max_length=18, null=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='gas_tank',
            field=models.CharField(max_length=14, null=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='goss_weight',
            field=models.IntegerField(null=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='installed_tire_code',
            field=models.CharField(max_length=9, null=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage_km',
            field=models.IntegerField(null=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='net_weight',
            field=models.IntegerField(null=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='original_tire_code',
            field=models.CharField(max_length=9, null=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='plate',
            field=models.CharField(max_length=7, null=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='rows_seats',
            field=models.IntegerField(null=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='wheel_drive',
            field=models.CharField(max_length=9, null=1),
        ),
    ]
