# Generated by Django 4.2.3 on 2023-07-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0002_springtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpringTest',
        ),
        migrations.AddField(
            model_name='spring',
            name='grade',
            field=models.IntegerField(default=2),
        ),
    ]
