# Generated by Django 4.2.3 on 2023-07-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0003_alter_car_bodywork_alter_car_car_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargocontrol',
            name='f1',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
        migrations.AlterField(
            model_name='cargocontrol',
            name='f10',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
        migrations.AlterField(
            model_name='cargocontrol',
            name='f2',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
        migrations.AlterField(
            model_name='cargocontrol',
            name='f3',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
        migrations.AlterField(
            model_name='cargocontrol',
            name='f4',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
        migrations.AlterField(
            model_name='cargocontrol',
            name='f5',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
        migrations.AlterField(
            model_name='cargocontrol',
            name='f6',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
        migrations.AlterField(
            model_name='cargocontrol',
            name='f7',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
        migrations.AlterField(
            model_name='cargocontrol',
            name='f8',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
        migrations.AlterField(
            model_name='cargocontrol',
            name='f9',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
        migrations.AlterField(
            model_name='cargocontrol',
            name='l1',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
        migrations.AlterField(
            model_name='cargocontrol',
            name='l10',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
        migrations.AlterField(
            model_name='cargocontrol',
            name='l2',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
        migrations.AlterField(
            model_name='cargocontrol',
            name='l3',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
        migrations.AlterField(
            model_name='cargocontrol',
            name='l4',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
        migrations.AlterField(
            model_name='cargocontrol',
            name='l5',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
        migrations.AlterField(
            model_name='cargocontrol',
            name='l6',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
        migrations.AlterField(
            model_name='cargocontrol',
            name='l7',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
        migrations.AlterField(
            model_name='cargocontrol',
            name='l8',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
        migrations.AlterField(
            model_name='cargocontrol',
            name='l9',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=1),
        ),
    ]
