# Generated by Django 4.2.3 on 2023-09-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0003_user_historicaluser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
    ]
