# Generated by Django 4.2.3 on 2023-07-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0003_delete_springtest_spring_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='spring',
            name='coils_red_amp_1',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='spring',
            name='coils_red_amp_2',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
