# Generated by Django 4.2.3 on 2023-07-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0004_alter_cargocontrol_f1_alter_cargocontrol_f10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=30, null=1),
        ),
        migrations.AlterField(
            model_name='spring',
            name='eccentricity1',
            field=models.DecimalField(decimal_places=3, default='-', max_digits=6),
        ),
        migrations.AlterField(
            model_name='spring',
            name='eccentricity2',
            field=models.DecimalField(decimal_places=3, default='-', max_digits=6),
        ),
    ]
