# Generated by Django 4.2.3 on 2023-07-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0004_spring_coils_red_amp_1_spring_coils_red_amp_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spring',
            old_name='coils_red_amp_1',
            new_name='coils_amp_1',
        ),
        migrations.RenameField(
            model_name='spring',
            old_name='coils_red_amp_2',
            new_name='coils_amp_2',
        ),
        migrations.AddField(
            model_name='spring',
            name='coils_red_1',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='spring',
            name='coils_red_2',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
