# Generated by Django 4.2.3 on 2023-07-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0005_rename_coils_red_amp_1_spring_coils_amp_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spring',
            name='eccentricity1',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='spring',
            name='eccentricity2',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
