# Generated by Django 4.2.3 on 2023-07-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0007_alter_spring_coil_direction_alter_spring_coils_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spring',
            name='luz1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='spring',
            name='luz2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
