# Generated by Django 4.2.3 on 2023-08-22 21:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0008_alter_spring_luz1_alter_spring_luz2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forces', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=[], size=None)),
                ('displacements', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=[], size=None)),
                ('spring', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='queryapp.spring')),
            ],
        ),
    ]
