# Generated by Django 4.2.3 on 2023-09-06 14:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0010_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forces',
            name='displacements',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='forces',
            name='forces',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='points',
            name='esf',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='points',
            name='posx',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='points',
            name='posy',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='points',
            name='posz',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=5), default=list, size=None),
        ),
    ]
